version: '3.4'

networks:
  dev:
    driver: bridge

services:
  server:
    depends_on:
      - db
    container_name: server
    ports:
      - "5000:5000"
    build:
      context: ./server
      dockerfile: Dockerfile
    
    environment:
      - ConnectionStrings__DefaultConnection=User ID=postgres;Password=postgres;Server=db;Port=5432;Database=DBTodo;Pooling=true;
    networks:
      - dev

  client:
    depends_on:
      - server
    container_name: client
    ports:
      - "4200:4200"
    build:
      context: ./client
      dockerfile: Dockerfile
    networks:
      - dev

  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - app_data:/var/lib/postgres/data
    networks:
      - dev

volumes:
  app_data: